name: Distribute

on:
  workflow_dispatch:
  release:
  
jobs:
  build_dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - name: publish
      run: |
        git config --global user.email "tip@gha"
        git config --global user.name "GHA"
        cd dist
        git init
        git add .
        git commit -am "deploy"
        git push --force git@github.com:arcanistzed/map-regions.git gh-pages
        rm -rf .git
        cd ..
