name: Distribute

on:
  workflow_dispatch:
  release:
  
jobs:
  build_dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - name: publish
      run: |
        git pull
        git subtree push --prefix dist origin gh-pages --force
